#!/usr/bin/env bash
#Install nginx on your web-01
#server
#Nginx should be listening on port 80

sudo apt update -y
sudo apt install nginx -y
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
