#!/usr/bin/env bash
#Install nginx on your web-01
#server
#Nginx should be listening on port 80

STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://google.com; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt install nginx -y
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
sudo echo "$STRING" > /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $REDIRECT" "$FILE"
sudo service nginx restart
