#!/usr/bin/env bash
# Script to setup an nginx server
indexFile=/var/www/html/index.nginx-debian.html
errorFile=/var/www/html/error.html
defaultWeb=/etc/nginx/sites-available/default
sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee $indexFile &&
sudo chmod 644 $indexFile
sudo chmod a+w $defaultWeb &&
sudo sed -i '/server_name _;/a\\n\terror_page 404 /error.html;\n\tlocation /error.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://google.com permanent;\n\t}\n' $defaultWeb &&
sudo chmod 644 $defaultWeb
sudo touch $errorFile
sudo chmod a+w $errorFile
sudo echo "Ceci n'est pas une page" > $errorFile
sudo chmod 644 $errorFile
sudo service nginx restart
