#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt -y install haproxy
frontend="\nforntend scorprogfront\n\tbind *:80\n\tdefault_backend app\n"
backend="\nbackend app\n\tbalance roundrobin\n\tserver 40506-web-01 52.91.125.60:80 check\n\tserver 40506-web-02 54.162.77.132:80 check\n"
file="/etc/haproxy/haproxy.cfg"
sudo echo "$frontend" >> "$file"
sudo echo "$backend" >> "$file"
sudo service haproxy restart
