#!/usr/bin/env bash
#a Bash script that generates a MySQL dump 
#and creates a compressed archive out of it.
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -cvzf "$(date '+%d-%m-%Y.tar.gz')" backup.sql
