#!/usr/bin/env bash
# Displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

i=1
while ((i < 101))
do
	if !((i % 15))
	then
		echo "FizzBuzz"
	elif !((i % 5))
	then
		echo "Buzz"
	elif !((i % 3))
	then
		echo "Fizz"
	else
		echo $i
	fi
	((i++))
done
