#!/usr/bin/env bash
# Displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
