#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r user pass uid gid full home shell
do
	echo -e "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $full"
done < /etc/passwd
