#!/usr/bin/env bash
# check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file


file="school"
if [ -f $file ]
then
	echo "school file exists"
		if [ -s $file ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f $file ]
			then echo "Regular File"
		fi
else
	echo "school file does not exist"
fi
